# fly.toml app configuration file generated for my-rails-interview-8da41q on 2025-06-05T03:41:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-rails-interview-8da41q'
primary_region = 'eze'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
